In [6]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import sys
sys.path.append('../../')

In [4]:
from scripts.loss_functions import CrossEntropy
from scripts.logistic_regression import LogisticRegressionClassifer

In [5]:
lr = LogisticRegressionClassifer()

In [7]:
iris = load_iris()
X = iris.data
Y = pd.get_dummies(iris.target).values # one-hot encoding 

In [11]:
y = Y[:,0]

In [12]:
lr.fit(X,y)

In [13]:
lr.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [15]:
lr.w

array([ 0.64906909,  2.09110951, -3.39509988, -1.23187507])

In [16]:
lr.b

0.3353898564665369

In [17]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
X = np.array([[1,2,3],[4,5,6]])

In [29]:
w = np.array([10,100,1000])

In [31]:
w.dot(X.T)

array([3210, 6540])

In [36]:
def value(x):
        return 1 / (1 + np.exp(-x))

In [39]:
y_pred = value(w.dot(X.T))

In [38]:
y = np.array([1,0])

In [46]:
np.dot(X.T,(y_pred-y).T)

array([4., 5., 6.])

In [43]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
(y_pred-y).T

array([0., 1.])

In [ ]:
CrossEntropy()

In [7]:
y = np.array([0,1,0,0,1])
p = np.array([0.1,0.03,0.4,0.2, 0.01])

In [8]:
- y * np.log(p) - (1 - y) * np.log(1 - p)

array([0.10536052, 3.5065579 , 0.51082562, 0.22314355, 4.60517019])

In [ ]:
p = np.clip(p, 1e-15, 1 - 1e-15)
return - y * np.log(p) - (1 - y) * np.log(1 - p)

In [12]:
np.random.uniform(-2, 2, (3,))

array([-0.95052162,  1.57814169,  0.55766775])

In [13]:
np.random.uniform(-2, 2, 3)

array([ 1.67974713,  0.41042365, -0.68850095])

In [12]:
Sigmoid.value(5)

0.9933071490757153

In [19]:
import numpy as np
class Test:

    @classmethod
    def __call__(self, x):
        return 1 / (1 + np.exp(-x))
    
    @classmethod
    def derivative(self, x):
        return self.value(x) * (1 - self.value(x))

In [21]:
a = Test()

In [22]:
a(5)

0.9933071490757153