In [1]:
import math
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import sys
sys.path.append('../../')

pd.options.display.max_rows=160

In [2]:
math.sqrt(4)

2.0

In [6]:
np.power(4,1/2)

2.0

In [20]:
np.abs(v1-v2).sum()

18

In [26]:
def minkowski_distance(p, v1, v2):
    if len(v1) != len(v2):
        raise ValueError("2 vectors must have same dimension")

    return np.power(np.sum(np.power(np.abs(v1-v2),p)),1/p)

In [27]:
minkowski_distance(np.inf, v1, v2)

1.0

In [31]:
max(np.abs(v1-v2))

7

In [29]:
v2

array([8, 8, 8])

In [7]:
v1 = np.array([1,2,3])

In [10]:
v2 = np.array([8,8,8])

In [13]:
np.abs(v1-v2)

array([7, 6, 5])

In [16]:
np.power(np.sum(np.power(np.abs(v1-v2),2)),1/2)

10.488088481701515

In [17]:
def euclidean_distance(v1, v2):
    """ 
    Calculate euclidean distance (l2 distance) between two vectors 

    Parameters
    ----------
    v1, v2: np.array

    Returns
    -------
    float
    """
    

    return math.sqrt(np.power(v1 - v2, 2).sum())

In [18]:
euclidean_distance(v1, v2)

10.488088481701515

In [10]:
from sklearn.linear_model import LogisticRegression

In [12]:
ll = LogisticRegression()

In [15]:
ll.fit(X,y)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
ll.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
pd.DataFrame(pd.get_dummies(ll.predict(X)).values)

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
5    1  0  0
6    1  0  0
7    1  0  0
8    1  0  0
9    1  0  0
10   1  0  0
11   1  0  0
12   1  0  0
13   1  0  0
14   1  0  0
15   1  0  0
16   1  0  0
17   1  0  0
18   1  0  0
19   1  0  0
20   1  0  0
21   1  0  0
22   1  0  0
23   1  0  0
24   1  0  0
25   1  0  0
26   1  0  0
27   1  0  0
28   1  0  0
29   1  0  0
30   1  0  0
31   1  0  0
32   1  0  0
33   1  0  0
34   1  0  0
35   1  0  0
36   1  0  0
37   1  0  0
38   1  0  0
39   1  0  0
40   1  0  0
41   1  0  0
42   1  0  0
43   1  0  0
44   1  0  0
45   1  0  0
46   1  0  0
47   1  0  0
48   1  0  0
49   1  0  0
50   0  1  0
51   0  1  0
52   0  1  0
53   0  1  0
54   0  1  0
55   0  1  0
56   0  1  0
57   0  1  0
58   0  1  0
59   0  1  0
60   0  1  0
61   0  1  0
62   0  1  0
63   0  1  0
64   0  1  0
65   0  1  0
66   0  1  0
67   0  1  0
68   0  1  0
69   0  1  0
70   0  0  1
71   0  1  0
72   0  1  0
73   0  1  0
74   0  1  0
75   0  1  0
76   0  1  0
77   0  0  1
78   0  1  0
79   0  1  0
80   0  1  0
81   0  1  0
82   0  1  0
83   0  0  1
84   0  1  0
85   0  1  0
86   0  1  0
87   0  1  0
88   0  1  0
89   0  1  0
90   0  1  0
91   0  1  0
92   0  1  0
93   0  1  0
94   0  1  0
95   0  1  0
96   0  1  0
97   0  1  0
98   0  1  0
99   0  1  0
100  0  0  1
101  0  0  1
102  0  0  1
103  0  0  1
104  0  0  1
105  0  0  1
106  0  1  0
107  0  0  1
108  0  0  1
109  0  0  1
110  0  0  1
111  0  0  1
112  0  0  1
113  0  0  1
114  0  0  1
115  0  0  1
116  0  0  1
117  0  0  1
118  0  0  1
119  0  0  1
120  0  0  1
121  0  0  1
122  0  0  1
123  0  0  1
124  0  0  1
125  0  0  1
126  0  0  1
127  0  0  1
128  0  0  1
129  0  0  1
130  0  0  1
131  0  0  1
132  0  0  1
133  0  0  1
134  0  0  1
135  0  0  1
136  0  0  1
137  0  0  1
138  0  0  1
139  0  0  1
140  0  0  1
141  0  0  1
142  0  0  1
143  0  0  1
144  0  0  1
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

In [21]:
pd.DataFrame(lr.predict(X))

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
5    1  0  0
6    1  0  0
7    1  0  0
8    1  0  0
9    1  0  0
10   1  0  0
11   1  0  0
12   1  0  0
13   1  0  0
14   1  0  0
15   1  0  0
16   1  0  0
17   1  0  0
18   1  0  0
19   1  0  0
20   1  0  0
21   1  0  0
22   1  0  0
23   1  0  0
24   1  0  0
25   1  0  0
26   1  0  0
27   1  0  0
28   1  0  0
29   1  0  0
30   1  0  0
31   1  0  0
32   1  0  0
33   1  0  0
34   1  0  0
35   1  0  0
36   1  0  0
37   1  0  0
38   1  0  0
39   1  0  0
40   1  0  0
41   1  0  0
42   1  0  0
43   1  0  0
44   1  0  0
45   1  0  0
46   1  0  0
47   1  0  0
48   1  0  0
49   1  0  0
50   0  1  0
51   0  1  0
52   0  1  0
53   0  1  0
54   0  1  0
55   0  1  0
56   0  1  0
57   0  1  0
58   0  1  0
59   0  1  0
60   0  1  0
61   0  1  0
62   0  1  0
63   0  1  0
64   0  1  0
65   0  1  0
66   0  1  0
67   0  1  0
68   0  1  0
69   0  1  0
70   0  0  1
71   0  1  0
72   0  1  0
73   0  1  0
74   0  1  0
75   0  1  0
76   0  1  0
77   0  1  0
78   0  1  0
79   0  1  0
80   0  1  0
81   0  1  0
82   0  1  0
83   0  0  1
84   0  1  0
85   0  1  0
86   0  1  0
87   0  1  0
88   0  1  0
89   0  1  0
90   0  1  0
91   0  1  0
92   0  1  0
93   0  1  0
94   0  1  0
95   0  1  0
96   0  1  0
97   0  1  0
98   0  1  0
99   0  1  0
100  0  0  1
101  0  0  1
102  0  0  1
103  0  0  1
104  0  0  1
105  0  0  1
106  0  0  1
107  0  0  1
108  0  0  1
109  0  0  1
110  0  0  1
111  0  0  1
112  0  0  1
113  0  0  1
114  0  0  1
115  0  0  1
116  0  0  1
117  0  0  1
118  0  0  1
119  0  0  1
120  0  0  1
121  0  0  1
122  0  0  1
123  0  0  1
124  0  0  1
125  0  0  1
126  0  0  1
127  0  0  1
128  0  0  1
129  0  0  1
130  0  0  1
131  0  0  1
132  0  0  1
133  0  1  0
134  0  0  1
135  0  0  1
136  0  0  1
137  0  0  1
138  0  0  1
139  0  0  1
140  0  0  1
141  0  0  1
142  0  0  1
143  0  0  1
144  0  0  1
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

In [2]:
from scripts.loss_functions import CrossEntropy
from scripts.logistic_regression import LogisticRegressionClassiferMulti

In [3]:
lr = LogisticRegressionClassiferMulti()

In [14]:
iris = load_iris()
X = iris.data
y = iris.target
Y = pd.get_dummies(iris.target).values # one-hot encoding 

In [5]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [30]:
lr.fit(X,Y,n_iterations=150)

In [31]:
lr.predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,

In [59]:
class Softmax:

    def __call__(self, x):
        exp_x = np.exp(x)
        sum_exp_x = np.sum(exp_x,axis=1)[np.newaxis].T
        return exp_x / sum_exp_x

In [60]:
s = Softmax()

In [70]:
x = np.array([[1,2,3,4],[11,16,17,18]])

In [71]:
s(x)

array([[3.20586033e-02, 8.71443187e-02, 2.36882818e-01, 6.43914260e-01],
       [6.06253464e-04, 8.99759918e-02, 2.44580104e-01, 6.64837651e-01]])

In [76]:
n_features = 2
n_classes = 3
limit = 1 / math.sqrt(n_features)

In [157]:
w = np.random.uniform(-limit, limit, (n_features, n_classes) )
b = np.array([0,0,0])

In [158]:
w

array([[ 0.23985093, -0.18115985,  0.28028103],
       [ 0.11811497, -0.29644452,  0.22218952]])

In [145]:
-0.00379647+0.6272511*2

1.25070573

In [141]:
b

array([10, 30, 70])

In [142]:
X = np.array([[1,2],[3,5],[6,9],[11,20]])
y = np.array([[1,0,0], [1,0,0], [0,1,0],[0,0,1]])

In [91]:
X

array([[ 1,  2],
       [ 3,  5],
       [ 6,  9],
       [11, 20]])

In [230]:
pp = s(np.dot(X,w)+b)

In [231]:
pp

array([[3.89306525e-01, 1.11523716e-01, 4.99169759e-01],
       [3.40689664e-01, 1.21234576e-02, 6.47186878e-01],
       [2.35080803e-01, 4.50602031e-04, 7.64468595e-01],
       [7.40402086e-02, 1.80875794e-07, 9.25959610e-01]])

In [229]:
np.argmax(s(np.dot(X,w)+b),axis=1)

array([2, 2, 2, 2])

In [233]:
(pp == pp.max(axis=1)[:,None]).astype(int)

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [232]:
np.zeros(pp.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
a = np.dot(X,w)+b

In [164]:
a

array([[ 0.47608086, -0.77404889,  0.72466008],
       [ 1.3101276 , -2.02570216,  1.95179071],
       [ 2.50214024, -3.7549598 ,  3.68139189],
       [ 5.00065949, -7.92164879,  7.52688181]])

In [165]:
y_pred = s(a)

In [219]:
y_pred

array([[3.89306525e-01, 1.11523716e-01, 4.99169759e-01],
       [3.40689664e-01, 1.21234576e-02, 6.47186878e-01],
       [2.35080803e-01, 4.50602031e-04, 7.64468595e-01],
       [7.40402086e-02, 1.80875794e-07, 9.25959610e-01]])

In [221]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [222]:
np.log(y_pred)

array([[ -0.94338826,  -2.19351801,  -0.69480904],
       [ -1.07678329,  -4.41261306,  -0.43512019],
       [ -1.44782598,  -7.70492602,  -0.26857433],
       [ -2.60314697, -15.52545526,  -0.07692466]])

In [223]:
y*np.log(y_pred)

array([[-0.94338826, -0.        , -0.        ],
       [-1.07678329, -0.        , -0.        ],
       [-0.        , -7.70492602, -0.        ],
       [-0.        , -0.        , -0.07692466]])

In [225]:
-np.sum(y*np.log(y_pred),axis=1)

array([0.94338826, 1.07678329, 7.70492602, 0.07692466])

In [220]:
np.clip(y_pred, 1e-1, 1 - 1e-1)

array([[0.38930653, 0.11152372, 0.49916976],
       [0.34068966, 0.1       , 0.64718688],
       [0.2350808 , 0.1       , 0.7644686 ],
       [0.1       , 0.1       , 0.9       ]])

In [197]:
np.round(y_pred-y,3)

array([[-0.611,  0.112,  0.499],
       [-0.659,  0.012,  0.647],
       [ 0.235, -1.   ,  0.764],
       [ 0.074,  0.   , -0.074]])

In [199]:
np.round(y_pred-y,3).T

array([[-0.611, -0.659,  0.235,  0.074],
       [ 0.112,  0.012, -1.   ,  0.   ],
       [ 0.499,  0.647,  0.764, -0.074]])

In [211]:
np.sum(y_pred-y,axis=0)

array([-0.9608828 , -0.87590204,  1.83678484])

In [207]:
np.dot(X.T, y_pred-y)

array([[-0.36369737, -5.84940031,  6.21309768],
       [-0.92140723, -8.71227624,  9.63368347]])

In [202]:
np.dot((y_pred-y).T,X).T

array([[-0.36369737, -5.84940031,  6.21309768],
       [-0.92140723, -8.71227624,  9.63368347]])

In [201]:
w

array([[ 0.23985093, -0.18115985,  0.28028103],
       [ 0.11811497, -0.29644452,  0.22218952]])

In [217]:
yy = y[:,0]
yy

array([1, 1, 0, 0])

In [218]:
1 - yy

array([0, 0, 1, 1])

In [188]:
X

array([[ 1,  2],
       [ 3,  5],
       [ 6,  9],
       [11, 20]])

In [189]:
y[:,0,None]*X

array([[1, 2],
       [3, 5],
       [0, 0],
       [0, 0]])

In [192]:
np.sum(y[:,0,None]*X,axis=0)/4

array([1.  , 1.75])

In [126]:
class Softmax:

    def __call__(self, x):
        if x.ndim == 1:
            x = np.array([x])
        
        x = x - np.array([x.max(axis=1)]).T
        
        exp_x = np.exp(x)
        sum_exp_x = np.sum(exp_x,axis=1)[np.newaxis].T
        return exp_x / sum_exp_x

In [127]:
s = Softmax()

In [128]:
s(X)

array([[2.68941421e-01, 7.31058579e-01],
       [1.19202922e-01, 8.80797078e-01],
       [4.74258732e-02, 9.52574127e-01],
       [1.23394576e-04, 9.99876605e-01]])

In [133]:
s(np.array([0,0.4]))

array([[0.40131234, 0.59868766]])

In [102]:
np.array([a])

array([[1, 2]])

In [110]:
s(np.array([1,2]))

array([[0.26894142, 0.73105858]])

In [111]:
s(np.array([-1,0]))

array([[0.26894142, 0.73105858]])

In [ ]:
y_pred = self.softmax(np.dot(self.w, X.T)+self.b)

In [117]:
X.max(axis=1).T

array([ 2,  5,  9, 20])

In [124]:
aa = np.array([a])

In [125]:
aa - np.array([aa.max(axis=1)]).T

array([[-1,  0]])

In [121]:
X - np.array([X.max(axis=1)]).T

array([[-1,  0],
       [-2,  0],
       [-3,  0],
       [-9,  0]])

In [79]:
np.zeros(n_classes)

array([0., 0., 0.])

In [67]:
0.0320586 + 0.08714432+ 0.23688282+ 0.64391426

1.0

In [64]:
9.00305732e-02+2.44728471e-01+6.65240956e-01

1.0000000002

In [61]:
x = np.array([[1,2,3],[4,5,6],[10,1,1],[1,1,1]])

In [57]:
np.sum(x,axis=1)[np.newaxis].T

array([[ 6],
       [15],
       [12],
       [ 3]])

In [44]:
x/np.array([[3,3,10,3]]).T

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ],
       [1.        , 0.1       , 0.1       ],
       [0.33333333, 0.33333333, 0.33333333]])

In [27]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [2.20264658e+04, 2.71828183e+00, 2.71828183e+00],
       [2.71828183e+00, 2.71828183e+00, 2.71828183e+00]])

In [28]:
np.exp([ 1,  2,  3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [29]:
exp_x = np.exp(x)

In [37]:
exp_x.T/np.sum(exp_x,axis=1)

array([[9.00305732e-02, 9.00305732e-02, 9.99753241e-01, 3.33333333e-01],
       [2.44728471e-01, 2.44728471e-01, 1.23379352e-04, 3.33333333e-01],
       [6.65240956e-01, 6.65240956e-01, 1.23379352e-04, 3.33333333e-01]])

In [36]:
exp_x

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [2.20264658e+04, 2.71828183e+00, 2.71828183e+00],
       [2.71828183e+00, 2.71828183e+00, 2.71828183e+00]])

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [14]:
s(np.array([[1,2,3],[4,5,6],[10,1,1]]))

array([[1.23089505e-04, 4.66126226e-02, 4.71234165e-02],
       [2.47231880e-03, 9.36239552e-01, 9.46499123e-01],
       [9.97404592e-01, 1.71478255e-02, 6.37746092e-03]])

In [16]:
lr.b

0.3353898564665369

In [17]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
X = np.array([[1,2,3],[4,5,6]])

In [29]:
w = np.array([10,100,1000])

In [31]:
w.dot(X.T)

array([3210, 6540])

In [36]:
def value(x):
        return 1 / (1 + np.exp(-x))

In [39]:
y_pred = value(w.dot(X.T))

In [38]:
y = np.array([1,0])

In [46]:
np.dot(X.T,(y_pred-y).T)

array([4., 5., 6.])

In [43]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
(y_pred-y).T

array([0., 1.])

In [ ]:
CrossEntropy()

In [7]:
y = np.array([0,1,0,0,1])
p = np.array([0.1,0.03,0.4,0.2, 0.01])

In [8]:
- y * np.log(p) - (1 - y) * np.log(1 - p)

array([0.10536052, 3.5065579 , 0.51082562, 0.22314355, 4.60517019])

In [ ]:
p = np.clip(p, 1e-15, 1 - 1e-15)
return - y * np.log(p) - (1 - y) * np.log(1 - p)

In [12]:
np.random.uniform(-2, 2, (3,))

array([-0.95052162,  1.57814169,  0.55766775])

In [13]:
np.random.uniform(-2, 2, 3)

array([ 1.67974713,  0.41042365, -0.68850095])

In [12]:
Sigmoid.value(5)

0.9933071490757153

In [19]:
import numpy as np
class Test:

    @classmethod
    def __call__(self, x):
        return 1 / (1 + np.exp(-x))
    
    @classmethod
    def derivative(self, x):
        return self.value(x) * (1 - self.value(x))

In [21]:
a = Test()

In [22]:
a(5)

0.9933071490757153